// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// co5300_qspi //
// ----------- //

#define co5300_qspi_wrap_target 0
#define co5300_qspi_wrap 1
#define co5300_qspi_pio_version 0

static const uint16_t co5300_qspi_program_instructions[] = {
            //     .wrap_target
    0x7004, //  0: out    pins, 4         side 0
    0xb842, //  1: nop                    side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program co5300_qspi_program = {
    .instructions = co5300_qspi_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = co5300_qspi_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config co5300_qspi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + co5300_qspi_wrap_target, offset + co5300_qspi_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
static inline void co5300_qspi_program_init(PIO pio, uint sm, uint offset, uint sclk_pin, uint d0_pin, uint baud) {
    pio_sm_config c = co5300_qspi_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, sclk_pin);
    sm_config_set_out_pins(&c, d0_pin, 4);
    sm_config_set_out_shift(&c, false, true, 8);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    float div = (float)clock_get_hz(clk_sys) / (2 * baud);
    sm_config_set_clkdiv(&c, div);
    pio_sm_set_consecutive_pindirs(pio, sm, sclk_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, d0_pin, 4, true);
    pio_gpio_init(pio, sclk_pin);
    pio_gpio_init(pio, d0_pin);
    pio_gpio_init(pio, d0_pin + 1);
    pio_gpio_init(pio, d0_pin + 2);
    pio_gpio_init(pio, d0_pin + 3);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

